<?php

declare(strict_types=1);

namespace LocalShip\Tests\Unit\Flow;

use LocalShip\Config\ConfigLoader;
use LocalShip\Flow\InitFlow;
use LocalShip\Util\Prompt;
use PHPUnit\Framework\TestCase;
use Symfony\Component\Yaml\Yaml;

final class InitFlowTest extends TestCase
{
    /**
     * @param array<int,string> $answers
     */
    private function flowWithAnswers(array $answers, ?array &$logsOut = null): InitFlow
    {
        $reader = static function () use (&$answers): string {
            $next = array_shift($answers);
            return null === $next ? '' : $next;
        };
        $logs   = [];
        $writer = function (string $line) use (&$logs): void {
            $logs[] = $line;
        };
        $logsOut = &$logs;

        $prompt = new Prompt($reader, $writer);

        return new InitFlow($prompt, $writer);
    }

    public function testGatherProducesValidConfig(): void
    {
        $flow = $this->flowWithAnswers([
            // Local URL (uses detected default).
            '',
            // Local path (uses detected default).
            '',
            // Active theme.
            'client-x-child',
            // SSH user.
            'runcloud',
            // SSH host.
            'srv.example.com',
            // Staging URL.
            'https://staging.client-x.com',
            // Staging path.
            '/home/runcloud/webapps/client-x-staging',
            // Production URL.
            'https://client-x.com',
            // Production path.
            '/home/runcloud/webapps/client-x',
        ]);

        $config = $flow->gather('/Users/me/Local Sites/client-x/app/public');

        // Top-level shape.
        self::assertSame('app/public', $config['path']);
        self::assertArrayHasKey('@staging', $config);
        self::assertArrayHasKey('@production', $config);

        // SSH aliases assemble user@host:path.
        self::assertSame(
            'runcloud@srv.example.com/home/runcloud/webapps/client-x-staging',
            $config['@staging']['ssh']
        );
        self::assertSame(
            'runcloud@srv.example.com/home/runcloud/webapps/client-x',
            $config['@production']['ssh']
        );

        // localship: block.
        self::assertSame('http://client-x.local', $config['localship']['local']['url']);
        self::assertSame(
            '/Users/me/Local Sites/client-x/app/public',
            $config['localship']['local']['path']
        );
        self::assertSame('client-x-child', $config['localship']['active_theme']);
        self::assertSame(['production'], $config['localship']['protected_envs']);
    }

    public function testGatherRoundTripsThroughConfigLoader(): void
    {
        $flow = $this->flowWithAnswers([
            'http://x.local',
            '/Users/me/Local Sites/x/app/public',
            '',
            'user',
            'host.example.com',
            'https://staging.x.com',
            '/var/www/x-staging',
            'https://x.com',
            '/var/www/x',
        ]);

        $config = $flow->gather('/some/unrelated/path');
        // The full produced config must validate cleanly through the production loader.
        $site   = (new ConfigLoader())->loadFromArray($config);

        self::assertSame('http://x.local', $site->local()->url());
        self::assertSame('https://x.com', $site->env('production')->url());
        self::assertTrue($site->env('production')->isProtected());
        self::assertFalse($site->env('staging')->isProtected());
    }

    public function testRenderProducesYamlParsableAsConfig(): void
    {
        $flow = $this->flowWithAnswers([
            'http://x.local',
            '/Users/me/Local Sites/x/app/public',
            '',
            'user',
            'host',
            'https://staging.x.com',
            '/p1',
            'https://x.com',
            '/p2',
        ]);
        $config = $flow->gather('/x');
        $yaml   = $flow->render($config);

        self::assertStringStartsWith('# Generated by `wp localship init`', $yaml);

        $parsed = Yaml::parse($yaml);
        self::assertSame('app/public', $parsed['path']);
        self::assertSame('http://x.local', $parsed['localship']['local']['url']);
    }

    public function testActiveThemeOmittedWhenBlank(): void
    {
        $flow = $this->flowWithAnswers([
            'http://x.local',
            '/p',
            // Empty theme.
            '',
            'user',
            'host',
            'https://staging.x.com',
            '/p1',
            'https://x.com',
            '/p2',
        ]);
        $config = $flow->gather('/x');

        self::assertArrayNotHasKey('active_theme', $config['localship']);
    }
}
