<?php

/**
 * The interactive init flow that writes per-site wp-cli.yml.
 *
 * @package LocalShip\Flow
 */

declare(strict_types=1);

namespace LocalShip\Flow;

use LocalShip\Util\LocalDetect;
use LocalShip\Util\Prompt;
use Symfony\Component\Yaml\Yaml;

/**
 * Asks the user for SSH details and per-env URLs/paths, then writes wp-cli.yml.
 *
 * Pure orchestration — no WP-CLI specifics, so the same flow is reachable from CloneCommand
 * (which runs init transparently when no config exists). Reader and writer are injected,
 * so tests drive the flow without a real TTY.
 */
final class InitFlow
{
    /** @var Prompt */
    private $prompt;

    /** @var callable(string):void */
    private $log;

    public function __construct(Prompt $prompt, callable $log)
    {
        $this->prompt = $prompt;
        $this->log    = $log;
    }

    /**
     * Run the prompts and produce a wp-cli.yml-shaped associative array.
     *
     * @return array<string,mixed>
     */
    public function gather(string $cwd): array
    {
        $detected = LocalDetect::fromCwd($cwd);

        if (null !== $detected['site_name']) {
            ($this->log)(sprintf('Detected Local site: %s', $detected['site_name']));
        }

        ($this->log)('');
        ($this->log)('-- Local --');
        $localUrl  = $this->prompt->ask('Local URL', $detected['url']);
        $localPath = $this->prompt->ask('Local WP path', $detected['path']);
        $theme     = $this->prompt->ask('Active theme slug (optional)', null, false);

        $sshUser = $this->prompt->ask('SSH user (used for both staging and production)', null);
        $sshHost = $this->prompt->ask('SSH host (e.g. srv-01.example.com)', null);

        ($this->log)('');
        ($this->log)('-- Staging --');
        $stagingUrl  = $this->prompt->ask('Staging URL (https://...)', null);
        $stagingPath = $this->prompt->ask('Staging WP path on the server', null);

        ($this->log)('');
        ($this->log)('-- Production --');
        $productionUrl  = $this->prompt->ask('Production URL (https://...)', null);
        $productionPath = $this->prompt->ask('Production WP path on the server', null);

        $config = [
            'path' => 'app/public',

            '@staging'    => [
                'ssh' => sprintf('%s@%s%s', $sshUser, $sshHost, $stagingPath),
            ],
            '@production' => [
                'ssh' => sprintf('%s@%s%s', $sshUser, $sshHost, $productionPath),
            ],

            'localship' => [
                'local'          => [
                    'url'  => $localUrl,
                    'path' => $localPath,
                ],
                'staging'        => [
                    'url'  => $stagingUrl,
                    'path' => $stagingPath,
                ],
                'production'     => [
                    'url'  => $productionUrl,
                    'path' => $productionPath,
                ],
                'protected_envs' => ['production'],
                'excludes_extra' => [],
            ],
        ];

        if ('' !== $theme) {
            $config['localship']['active_theme'] = $theme;
        }

        return $config;
    }

    /**
     * Render the gathered config as YAML suitable for writing to wp-cli.yml.
     *
     * @param array<string,mixed> $config
     */
    public function render(array $config): string
    {
        $banner = "# Generated by `wp localship init`. Edit freely.\n"
                . "# See https://github.com/fabiomsnunes/localship for documentation.\n\n";

        return $banner . Yaml::dump($config, 4, 2, Yaml::DUMP_MULTI_LINE_LITERAL_BLOCK);
    }
}
